"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-568lp1vx2-wi8@vpx(0l7_&cy_-%a-h&&1b5vv&4m*r1vf4(gk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки бота
TOKEN = 'YOUR_TOKEN'
QUESTIONS = [
    '1)	Что Вам больше нравится:',
    '2)	Чувствуете ли Вы связь с животными?',
    '3)	Как бы Вы себя описали:',
    '4)	Вы предпочитаете работать в группе или в одиночку:',
    '5)	Вы уверенный человек?',
    '6)	Выберите одну стихию?',
    '7)	Какого питомца Вы бы завели?'
]

ANSWERS = [
    {
        'африканская саванна': 2,
        'тропические цветы': 3,
        'снежные горы': 0,
        'хвойный лес': 1
    },
    {
        'нет': 1,
        'конечно': 3,
        'зависит от обстоятельств': 2,
        'люблю их больше, чем людей': 0
    },
    {
        'умный': 1,
        'красивый': 2,
        'везучий': 3,
        'трудолюбивый': 0
    },
    {
        'в одиночку': 3,
        'в группе': 2,
        'зависит от задачи': 0,
        'люблю работать в паре': 1
    },
    {
        'стараюсь им быть': 3,
        'нет': 1,
        'да': 2,
        'я обдумываю каждое действие': 0
    },
    {
        'воздух': 0,
        'огонь': 2,
        'вода': 3,
        'земля': 1
    },
    {
        'кота': 3,
        'собаку': 2,
        'птичку': 0,
        'игуану': 1
    }
]

PHOTOS = {
    'змея': 'https://tinyurl.com/3tthhf9f',
    'сова': 'https://tinyurl.com/39jdwywz',
    'волк': 'https://tinyurl.com/wh226t7s',
    'лев': 'https://tinyurl.com/yckkxc62',
}

# Настройки почтовой рассылки
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'USER'
EMAIL_HOST_PASSWORD = 'PASSWORD'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'NewsPortal.notifications@yandex.ru'
DEFAULT_CONTACT_EMAIL = ['acharaevruslan@yandex.ru',]  # Здесь будет храниться адрес сотрудника зоопарка для связи
DEFAULT_FEEDBACK_EMAIL = ['acharaevruslan@yandex.ru',]  # Здесь будет храниться адрес для сбора отзывов
