# Generated by Django 5.1.1 on 2024-09-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_profile_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='question',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.TextField(default='Не пройдено'),
        ),
    ]
