# Generated by Django 5.1.1 on 2024-09-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_profile_points_profile_question_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totem',
            field=models.TextField(default='Не определено', verbose_name='Тотемное животное'),
        ),
    ]
