# Generated by Django 5.1.1 on 2024-09-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_profile_totem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
